apiVersion: v2
name: spring-boot-example-rest-http
version: 0.0.1-SNAPSHOT
description: A Helm chart to build and deploy Spring Boot application with REST endpoints
keywords:
  - runtimes
  - spring-boot
icon: https://avatars.githubusercontent.com/u/558276?s=400&u=19efc68c74844b2e092698a8a7a752921edcdc19&v=4
dependencies:
  - alias: app
    name: spring-boot-example-app
    version: 0.0.4
    repository: http://snowdrop.github.io/helm
