name: "Pull Request Build"
on:
  workflow_dispatch:
  pull_request:
jobs:
  linux-build-local:
    name: PR - Linux - JVM ${{ matrix.java }} - Local
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Java
        uses: actions/setup-java@v2.3.1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: 'maven'
      - name: Build
        run: ./mvnw -s .github/mvn-settings.xml clean verify
  linux-build-ocp:
    name: PR - Linux - JVM ${{ matrix.java }} - OpenShift ${{ matrix.openshift }}
    needs: linux-build-local
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
        openshift: [ v3.11.0 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Java
        uses: actions/setup-java@v2.3.1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: 'maven'
      - name: Setup OpenShift
        uses: manusa/actions-setup-openshift@v1.1.3
        with:
          oc version: ${{ matrix.openshift }}
          dns ip: 1.1.1.1
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Project using Dekorate
        run: |
          oc new-project dekorate
          ./run_tests_with_dekorate.sh
      - name: Delete Project using Dekorate
        run: oc delete project dekorate
      - name: Clean folder
        run: ./mvnw -s .github/mvn-settings.xml clean
      - name: Build Project using S2i
        run: |
          oc new-project s2i
          ./run_tests_with_s2i.sh "${{ github.event.pull_request.head.repo.owner.html_url }}/${{ github.event.pull_request.head.repo.name }}" ${{ github.head_ref }}
      - name: Delete Project using S2i
        run: oc delete project s2i
      - name: Build Project using Helm
        run: |
          oc new-project helm
          ./run_tests_with_helm_in_ocp.sh "${{ github.event.pull_request.head.repo.owner.html_url }}/${{ github.event.pull_request.head.repo.name }}" ${{ github.head_ref }}
      - name: Delete Project using Helm
        run: oc delete project helm
  linux-build-kubernetes:
    name: PR - Linux - JVM ${{ matrix.java }} - Kubernetes
    needs: linux-build-local
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Java
        uses: actions/setup-java@v2.3.1
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
          cache: 'maven'
      - name: Kubernetes KinD Cluster
        uses: container-tools/kind-action@v1
        with:
          version: v0.11.1
          registry: true
      - name: Build Project using Helm
        run: |
          kubectl create namespace helm
          ./run_tests_with_helm_in_k8s.sh $KIND_REGISTRY helm
      - name: Delete Project using Helm
        run: kubectl delete namespace helm
      # - name: Build Project using Dekorate
      #  run: |
      #    kubectl create namespace k8s
      #    ./mvnw -s .github/mvn-settings.xml clean verify -Pkubernetes,kubernetes-it -Ddekorate.docker.registry=kind-registry:5000 -Dkubernetes.namespace=k8s -Ddekorate.push=true
